spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/chat_dev
    username: testuser
    password: 5678
  jpa:
    properties:
      hibernate.default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.jackson2: INFO